### ISSUE TITLE
serious question: is this actually better than the actual cbf?

### ISSUE THREAD

**Issue by ghost** [Alphalaneous/Click-After-Frames#1]
because it like cbf except you can actually modify the input lag but with cbf the imput percision will be link to your gaming keyboard/mouse polling rate (ex 1000/8000) so what now i will be waiting for the anwser.

**Comment by Alphalaneous** [comment]
This is a joke mod meant to add input delay as the name and description imply, it is not meant for serious use, rather for jokes and potentially challenges

**Comment by ghost** [comment]
> This is a joke mod meant to add input delay as the name and description imply, it is not meant for serious use, rather for jokes and potentially challenges

but however as this mod actually allow you to modify the input lag regardless of polling rates of the device (like keyboard or mice/mouse) unironically this mod might rival the Click Between Frames since cbf input percision is based on polling rate of your device, let says you have 1000hz mouse or keyboard you will have 1ms response time but with 8000hz polling rate you will have 0.125ms response time but with this mod if you set 0 ms in the mod setting you will have literally no response time what so ever, regardless of polling rate of the devices you use. it like the fps bypass except it only modify the input tracking instead and keep the game 2.2 physics and plus little to no lag. unironically this mod might be good for cheap gaming keyboard/mouse with 125hz polling rate (like you bought one from amazon kinda like 5$ lol). what do you think? i know this mod is joke but however.

**Comment by Alphalaneous** [comment]
That’s not how it works, any input delay is added on to existing delay, I cannot poll faster than the input device, all this does is sleep the chosen amount of time after an input is pressed

**Comment by ghost** [comment]
> That’s not how it works, any input delay is added on to existing delay, I cannot poll faster than the input device, all this does is sleep the chosen amount of time after an input is pressed

Ah so in conclusion: modify the input lag to 0 is not better than device with polling rate of 1000hz example i did bit of testing this mod for comparsion Click After Frames, 0 input delay setting vs Click On Steps on mobile on straight flying and it felt somewhat the same as playing as click on step except being slightly worse. yeah your are right the straight flying feel bit or way too off for being true 0 input lag i though this be unironically better than click on steps but no
